### ISSUE TITLE
Attributes recipe overrides defaults

### ISSUE THREAD

**Issue by slbmeh** [chef-cookbooks/postfix#98]
In commit d972e58fa49fcbb6dba3a6a8578babc6e579d39e attributes were moved to a recipe which will override defaults set in a wrapper cookbook that includes postfix.  Possibly `node.default_unless` instead?

**Comment by bkw** [comment]
+1

**Comment by drywheat** [comment]
I think this @slbmeh is spot on with his suggestion. The following code block was taken from the current version of `_attributes` recipe:
https://github.com/opscode-cookbooks/postfix/blob/master/recipes/_attributes.rb#L33-L40

```ruby
if node['postfix']['main']['smtp_sasl_auth_enable'] == 'yes'
  node.default['postfix']['sasl_password_file'] = "#{node['postfix']['conf_dir']}/sasl_passwd"
  node.default['postfix']['main']['smtp_sasl_password_maps'] = "hash:#{node['postfix']['sasl_password_file']}"
  node.default['postfix']['main']['smtp_sasl_security_options'] = 'noanonymous'
  node.default['postfix']['sasl']['smtp_sasl_user_name'] = ''
  node.default['postfix']['sasl']['smtp_sasl_passwd']    = ''
  node.default['postfix']['main']['relayhost'] = ''
end
```

This implementation prevents users from manipulating the attribute values listed above at the **default** level. Hence, the following approach does not work albeit a standard way of creating a wrapper cookbook:

```ruby
# inside my wrapper recipe I enable SASL and try to set some basic config values
node.default['postfix']['main']['smtp_sasl_auth_enable'] = 'yes'

# these values will all be blank when the template evaluates :-(
node.default['postfix']['sasl']['smtp_sasl_user_name'] = 'gino'
node.default['postfix']['sasl']['smtp_sasl_passwd']    = 'olive'
node.default['postfix']['main']['relayhost'] = '[smtp.drywheat.io]:25'

include_recipe 'postfix'
include_recipe 'postfix::sasl_auth'
```

**Comment by jonathanhoskin** [comment]
Are they any plans to fix this?

**Comment by fstradiotti** [comment]
+1

**Comment by chasebolt** [comment]
default_unless has some caveats to it and is rarely used; though it would work in this case, this goes against best practices.

A wrapper cookbook should always use a precedence level above default due to evaluation ordering. force_default, override, and force_override are the next 3 levels that should be used for a wrapper.

https://docs.chef.io/attributes.html#attribute-precedence

**Comment by wk8** [comment]
Totally agree with this issue. Makes it quite impossible to wrap this cookbook. I don't even understand why it was done that way?

**Comment by wk8** [comment]
"A wrapper cookbook should always use a precedence level above default due to evaluation ordering. force_default, override, and force_override are the next 3 levels that should be used for a wrapper." => I heartily disagree with that statement. Wrapper cookbooks should always use default as much as possible.

**Comment by wk8** [comment]
If only because that makes it impossible to use credentials for SASL contained in an encrypted data bag. Not great at all.

**Comment by chasebolt** [comment]
It was moved to a recipe because you couldn't  wrap if then conditions on an attribute, that requires an override to enable, and then override the attributes inside of the condition.

If someone can create a pull request with a version that works, I'd be happy to look it over. This was discussed in the chef chat and the only solution to keeping the if then conditions was to move them into a recipe.

**Comment by maoueh** [comment]
@chasebolt I agree that it's better to perform conditional and derived attributes in a `_attributes` recipe file. It's simply too late when doing it in attributes file.

Using `default_unless` would indeed work both you have concerned about it. It's not best practices for regular usage in attributes file. But here, I think it make total sense because you want to redefine the `default` level only if it's not set yet by anyone else. If set, use provided default value instead.

**Comment by maoueh** [comment]
Created !112 so we can discuss possible solutions.
